<a href="https://colab.research.google.com/github/Dpaste20/Numpy_Practice/blob/main/Numpy_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**Initialization**

In [ ]:
a =  np.array([1,2,3])
print(a)

[ 4  8 12]


Data Types

In [ ]:
# Integer
int_arr  =  np.array([20,16,1111])
int_arr2  =  np.array([20,16,1111],dtype='int16')
print(int_arr)
print(int_arr.dtype)
print(int_arr2.dtype)

# float
float_arr = np.array([1.6,2.0,11.11])
print(float_arr)
print(float_arr.dtype)

# Boolean array
bool_array = np.array([True, False, True])
print(bool_array)
print(bool_array.dtype)

[  20   16 1111]
int64
int16
[ 1.6   2.   11.11]
float64
[ True False  True]
bool


**Various ways to create NumPy arrays:**

In [ ]:
np_array =  np.array([1,2,3,4,5])
print(np_array)

[1 2 3 4 5]


In [ ]:
range_array = np.arange(10)
print(range_array)

range_array = np.arange(1,10)
print(range_array)

range_array = np.arange(1,10,2)
print(range_array)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [ ]:
zero_array = np.zeros(5)
print(zero_array)

one_array = np.ones(5)
print(one_array)


[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [ ]:
random_array =  np.random.rand(4)
print(random_array)

[0.83516851 0.88579448 0.08675022 0.04725297]


In [ ]:
random_ints_1d = np.random.randint(0, 11, size=5)
print(random_ints_1d)

[4 3 6 0 2]


In [ ]:
random_ints_2d = np.random.randint(1, 101, size=(3, 4))
print(random_ints_2d)

[[51 69 61 64]
 [61 38 42 91]
 [ 5 88 54 35]]


In [ ]:
# Generate a 1D array of 10 random booleans
random_bools_1d = np.random.randint(0, 2, size=10, dtype=bool)
print(random_bools_1d)
# Output: [ True False  True False False  True False False False  True]

# Generate a 2D array of shape (3, 4) with random booleans
random_bools_2d = np.random.randint(0, 2, size=(3, 4), dtype=bool)
print(random_bools_2d)

[False  True  True  True False False False  True  True  True]
[[False  True False False]
 [False False  True  True]
 [ True False  True  True]]
